<?php
/**
 * DO NOT EDIT: PAGE GENERATED BY CLASS.AUTOLOAD
 */
namespace seagoj\devtools;

// Register custom autoload function for current namespace
spl_autoload_register(__NAMESPACE__."\__autoload");

/**
 * __autoload Function
 * Magic function that is kicked off when an undefined object is created.
 * Instantiates class autoload to search for and include desired class definition.
 *
 * @access	public
 * @param	string	$class	Name of class to be instantiated
 * @return	void
 */
function __autoload($class) {
	require_once("../../autoload/src/autoload.php");
	$load = new autoload(substr($class,strlen(__NAMESPACE__)+1));
	require_once($load->path);
}

require_once("../lib/autoload/src/autoload.php");
require_once("../lib/dbg/src/dbg.php");
require_once("../lib/model/src/model.php");
require_once("../lib/randData/src/randData.php");
require_once("../lib/unit/src/unit.php");
require_once("autoloadTest.php");
require_once("dbgTest.php");
require_once("unitTest.php");
